# Generated by Django 4.1.7 on 2023-02-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
