# Generated by Django 4.1.7 on 2023-02-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productlist',
        ),
    ]
